### ISSUE TITLE
Widgets

### ISSUE THREAD

**Issue by ashleyggiuli** [GoGaucho/GoGauchoiOSFeedbacks#58]
My meal plan and schedule widgets are saying to log into GoGaucho. I have logged in so that I can see my schedule on the app so I am confused as to why the widgets are still asking me to log in.

**Comment by a211212abc** [comment]
Thanks for your feedback! And Yes, we did find this bug. The problem caused by the changing of university's quarter index. We've fixed it in the next version. Sorry for the inconvenience and hope you have a great quarter my friend.

**Comment by ashleyggiuli** [comment]
Thank you so much! Really love the app btw!
